version: '2'

services:
    webserver:
        #image: helrick/forcast
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - .env
        expose:
            - 80
        ports:
            - ${APACHE2_PORT}:80
        volumes:
            - ./mongodb:/data/db
            - ./src:/var/www/html/src
            - ./jbrowse:/var/www/html/jbrowse
        command: >
            bash -c "sudo mongod --fork --logpath /var/log/mongodb.log
            && cd /var/www/html/jbrowse
            && ./setup.sh
            && chmod +x /var/www/html/src/setup/data.sh && /var/www/html/src/setup/data.sh
            && env | grep '^ATTEMPT_[0-9]\+_FILE\|^ATTEMPT_[0-9]\+_DESC' >
            /var/www/html/config/primer3settings.conf
            && sudo service apache2 start
            && tail -f /proc/self/fd/1"
